version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
          - gradle-{{ checksum "build.gradle" }}
          - gradle-{{ checksum  "sample/build.gradle" }}
          - gradle-{{ checksum  "library/build.gradle" }}

    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - save_cache:
        keys:
          - gradle-{{ checksum "build.gradle" }}
          - gradle-{{ checksum  "sample/build.gradle" }}
          - gradle-{{ checksum  "library/build.gradle" }}
        paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper

    - run:
        name: Build
        command: ./gradlew build

    - store_artifacts:
        path: library/build/reports
        destination: reports
    - store_test_results:
        path: library/build/test-results

    - store_artifacts:
        path: sample/build/reports
        destination: reports
    - store_test_results:
        path: sample/build/test-results